---
apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    name: mysql-db
spec:
  volumes:
    - name: mysqlcm-vol
      configMap:
        name: mysql-cm
    - name: secret-vol
      secret:
        secretName: mysql-secret 
  containers:
    - name: mysql-db
      image: mysql:8.0-debian
      resources:
        limits:
          memory: "1024Mi"
          cpu: "1000m"
      ports:
        - containerPort: 3306
      volumeMounts:
        - name: mysqlcm-vol
          mountPath: /vvr
        - name: secret-vol
          mountPath: /secret
      env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: mysql-cm
              key: rootpassword
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mysql-cm
              key: database
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: mysql-cm
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: mysql-cm
              key: password
     