---
apiVersion: v1
kind: Pod
metadata:
  name: test1
  labels:
    name: without
spec:
  containers:
  - name: vsh
    image: httpd:2.4
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
  