---
apiVersion: v1
kind: Pod
metadata:
  name: without-toleration
  labels:
    name: without
spec:
  containers:
  - name: vsh
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
