---
apiVersion: v1
kind: Pod
metadata:
  name: toleration
  labels:
    name: toleration
spec:
  tolerations:
    - key: course
      operator: Equal
      value: aws
      effect: NoSchedule
  containers:
    - name: container
      image: nginx
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 80
