---
apiVersion: v1
kind: Pod
metadata:
  name: httpd-pod
spec:
  containers:
    - name: httpd
      image: httpd:2.4
      ports:
        - containerPort: 80
          protocol: "TCP"
      resources:
        limits:
          cpu: 500m
          memory: 256Mi