---
apiVersion: v1
kind: Pod
metadata:
  name: other
spec:
  containers:
    - name: httpd
      image: httpd:2.4
      ports:
        - containerPort: 80
    - name: tomcat
      image: tomcat:11.0
      