---
apiVersion: v1
kind: Pod
metadata:
  name: other
spec:
  containers:
    - name: httpd
      image: httpd:2.4
      resources:
        limits:
          cpu: 500m
          memory: 256Mi
    - name: tomcat
      image: tomcat:11.0
      resources:
        limits:
          cpu: 500m
          memory: 256Mi
      