---
apiVersion: v1
kind: Pod
metadata:
  name: twopods
spec:
  containers:
    - name: httpd
      image: httpd:2.4
      ports:
        - containerPort: 80
    - name: nginx
      image: nginx:1.25
      ports:
        - containerPort: 8080
 