---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - name: apache
        image: httpd:2.4
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m" 
        ports:
        - containerPort: 80
