---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deploy
spec:
  minReadySeconds: 10
  replicas: 3
  selector:
    matchLabels:
      app: apache
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels: 
        app: apache       
        version: "1.2"
    spec:
      containers:
        - name: alpine
          image: alpine
          ports:
            - containerPort: 80
          args:
            - sleep
            - 1d
          readinessProbe:
            httpGet:
               path: /
               port: 80
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
        - name: apache
          image: httpd:2.4
          resources:
            limits:
              cpu: 500m
              memory: 500Mi

      