---
apiVersion: v1
kind: Service
metadata:
  name: apache-svc
spec:
  type: NodePort
  selector:
    app: apache
  ports:
    - name: apache-port
      targetPort: 80
      port: 80
      nodePort: 30001