---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rqconfigmap
data:
  RABBITMQ_CONFIG_FILE: /etc/pitstop/rabbitmq.conf



---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
spec:
  minReadySeconds: 10
  replicas: 1
  selector:
   matchLabels:
    app: rabbitmq
  serviceName: rabbitmq-svc
  template:
   metadata:
    labels: 
      app: rabbitmq
      version: "1.0"
   spec:
    containers:
      - name: rabbitmq
        image: rabbitmq:3-management-alpine
        ports:
          - containerPort: 15672      
          - containerPort: 5672
        env:
          - name: RABBITMQ_CONFIG_FILE
            valueFrom:
             configMapKeyRef:
              name: rqconfigmap
              key: RABBITMQ_CONFIG_FILE
        volumeMounts:
          - name: rabbitmqdata
            mountPath: /var/lib/rabbitmq:/etc/pitstop/   
    volumes:
      - name: rabbitmqdata
        persistentVolumeClaim:
          claimName: rabbitmq
          readOnly: false


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq
spec:
  resources:
    requests:
      storage: 2Gi
  storageClassName: managed-csi
  accessModes:
    - ReadWriteOnce

  
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-svc
spec:
  clusterIP: None
  selector:
    app: rabbitmq
  ports:
    - name: rabbitmq
      port: 15672
      targetPort: 15672
    - name: rabbimq1
      port: 5672
      targetPort: 5672


  

        
