---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sqlconfigmap
data: 
  agreement: "Y"
  id: Developer
  password: 8jkGh47hnDw89Haq8LN2


---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sqlserver
spec:
  minReadySeconds: 10
  replicas: 1
  selector:
   matchLabels:
    app: sqlserver
  serviceName: sql-svc
  template:
   metadata:
    labels: 
      app: sqlserver
      version: "1.0"
   spec:
    containers:
      - name: sqlserver
        image: mcr.microsoft.com/azure-sql-edge
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 1433
        env:
          - name: ACCEPT_EULA
            valueFrom:
            configMapKeyRef:
              name: sqlconfigmap
              key: agreement
          - name: MSSQL_PID
            valueFrom:
            configMapKeyRef:
              name: sqlconfigmap
              key: id
          - name: SA_PASSWORD
            valueFrom:
            configMapKeyRef:
              name: sqlconfigmap
              key: password
        volumeMounts:
          - name: sqlserverdata
            mountPath: /var/opt/mssql   
    volumes:
      - name: sqlserverdata
        persistentVolumeClaim:
          claimName: sqlserver
          readOnly: false

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sqlserver
spec:
  resources:
    requests:
      storage: 2Gi
  storageClassName: managed-csi
  accessModes:
    - ReadWriteOnce
       
 
  
---
apiVersion: v1
kind: Service
metadata:
  name: sql-svc
spec:
  selector:
    app: sqlserver
  ports:
    - name: sqlserver
      port: 1434
      targetPort: 1433
  


  

        
