---
apiVersion: apps/v1  
kind: Deployment
metadata:
  name: timeservice-deploy
spec:
  minReadySeconds: 10
  replicas: 1
  selector: 
    matchLabels:
      app: timeservice   
  template: 
   metadata:
    labels:
      app: timeservice
      version: "1.0"
   spec:
     containers:
       - name: timeservice
         image: pitstop/timeservice:1.0
         env:
           - name: DOTNET_ENVIRONMENT
             value: Production
         resources:
          limits:
           cpu: 500m
           memory: 256Mi



