---
apiVersion: apps/v1  
kind: Deployment
metadata:
  name: vehiclemanagementapi-deploy
spec:
  minReadySeconds: 10
  replicas: 1
  selector: 
    matchLabels:
      app: vehiclemanagementapi     
  template: 
   metadata:
    labels:
      app: vehiclemanagementapi
      version: "1.0"
   spec:
     containers:
       - name: vehiclemanagementapi
         image: pitstop/vehiclemanagementapi:1.0
         ports:
           - containerPort: 5000
         env:
           - name: ASPNETCORE_ENVIRONMENT
             value: Production
         resources:
          limits:
           cpu: 500m
           memory: 256Mi


---
apiVersion: v1
kind: Service
metadata:
  name: vehicleapi-svc
spec:
  type: NodePort
  selector:
    app: vehiclemanagementapi
  ports:
    - name: vehiclemanagementapi 
      port: 5000
      targetPort: 5000
      nodePort: 31002
    
