---
apiVersion: apps/v1  
kind: Deployment
metadata:
  name: webapp-deploy
spec:
  minReadySeconds: 10
  replicas: 1
  selector: 
    matchLabels:
      app: webapp  
  template: 
   metadata:
    labels:
      app: webapp
      version: "1.0"
   spec:
     containers:
       - name: webapp
         image: pitstop/webapp:1.0
         ports:
          - containerPort: 7005
         env:
           - name: DOTNET_ENVIRONMENT
             value: Production
         resources:
          limits:
           cpu: 500m
           memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: webapp
spec:
  type: NodePort
  selector:
    app: webapp
  ports:
    - name: webapp
      port: 7005
      targetPort: 7005
      nodePort: 31005



