---
apiVersion: apps/v1  
kind: Deployment
metadata:
  name: workshopmanagementeventhandler-deploy
spec:
  minReadySeconds: 10
  replicas: 1
  selector: 
    matchLabels:
      app: workshopmanagementeventhandler   
  template: 
   metadata:
    labels:
      app: workshopmanagementeventhandler
      version: "1.0"
   spec:
     containers:
       - name: workshopmanagementeventhandler
         image: pitstop/workshopmanagementeventhandler:1.0
         env:
           - name: DOTNET_ENVIRONMENT
             value: Production
         resources:
          limits:
           cpu: 500m
           memory: 256Mi



