---
apiVersion: apps/v1
kind: StatefulSet
metadata:
 name: mango
spec:
  minReadySeconds: 5
  replicas: 2
  selector: 
    matchLabels:
      app: mango
  serviceName: mango-svc
  template: 
    metadata:
     labels:
       app: mango
       version: v1.0
    spec:
      containers:
        - name: mango-db
          image: mongo:5.0.24
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: example
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mango-vol
              mountPath: /data/db
  volumeClaimTemplates: 
    - metadata:
        name: mango-vol
      spec:
        resources:
          requests:
            storage: 2Gi
        storageClassName: managed-csi
        accessModes:
          - ReadWriteOnce
              