
---
apiVersion: v1
kind: Pod
metadata:
  name: positive
  labels:
    app: httpd
spec:
    containers:
      - name: httpd
        image: httpd:2.4
        ports:
          - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
        resources:
            limits:
              cpu: 500m
              memory: 256Mi
       

---
apiVersion: v1
kind: Pod
metadata:
  name: negative
  labels:
    app: httpd
spec:
    containers:
      - name: httpd
        image: httpd:2.4
        ports:
          - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
        readinessProbe:
          httpGet:
            path: /admin
            port: 80
        resources:
            limits:
              cpu: 500m
              memory: 256Mi
        