---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deploy
spec:
  minReadySeconds: 10
  replicas: 4
  selector:
    matchLabels:
      app: httpd
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels: 
        app: httpd        
        version: "1.2"
    spec:
      containers:
        - name: httpd
          image: nginx
          ports:
            - containerPort: 80
          