---
apiVersion: v1
kind: Service
metadata:
  name: httpd-svc
spec:
  type: NodePort
  selector:
    app: httpd
  ports:
    - name: httpd-port
      targetPort: 80
      port: 80
      nodePort: 30005