---
apiVersion: batch/v1  
kind: CronJob
metadata:
 name : cj1
spec:
  schedule: "* * * * *"
  jobTemplate:
    metadata:
      name: cj
    spec:
      template:
        metadata:
          name: test
          labels:
            app: job
        spec:
          restartPolicy: Never
          containers:
            - name: apache
              image: httpd:2.4
              args:
                - sleep
                - 10s
              