---
apiVersion: batch/v1
kind: Job
metadata:
  name: sample-job 
spec:
  template:
    metadata:
      name: vsh
      labels:
        app: apache
    spec:
      restartPolicy: Never
      containers:
        - name: sample-cntr
          image: alpine
          args:
            - sleep 
            - 10s
        
