---
apiVersion: v1
kind: Pod
metadata:
  name: vsh
  labels:
    name: vsh
    env: dev
spec:
  nodeSelector:
    test: prod
  containers:
  - name: cntr-1
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80 
