---
apiVersion: v1
kind: Service
metadata:
  name: check-svc
spec:
  selector:
    app: nginx
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80



---
apiVersion: v1
kind: Pod
metadata:
  name: positive
  labels:
    app: nginx
spec:
    containers:
      - name: nginx
        image: nginx
        ports:
          - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
        resources:
          limits:
            cpu: 1000m
            memory: 500Mi

---
apiVersion: v1
kind: Pod
metadata:
  name: negative
  labels:
    app: nginx
spec:
    containers:
      - name: nginx
        image: nginx
        args: 
          - sleep
          - 1d
        ports:
          - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
        readinessProbe:
          httpGet:
            path: /admin
            port: 80
        resources:
          limits:
            cpu: 1000m
            memory: 500Mi