---
apiVersion: v1
kind: Pod
metadata:
  name: positive
  labels:
    app: nginx
spec:
    containers:
      - name: nginx
        image: nginx
        ports:
          - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
        

---
apiVersion: v1
kind: Pod
metadata:
  name: negative
  labels:
    app: nginx
spec:
    containers:
      - name: nginx
        image: nginx
        args: 
          - sleep
          - 1d
        ports:
          - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
       
