---
apiVersion: v1
kind: Pod
metadata:
  name: trail6
spec:
  restartPolicy: OnFailure
  initContainers:
    - name: init1
      image: alpine
      args:
         - sleep
         - 30s
    - name: init2
      image: alpine
      args:
         - sleep
         - 30s
    - name: init3
      image: alpine
      args:
         - sleep
         - 30s
  containers:
    - name: httpd
      image: httpd:2.4
    - name: sidecaer1
      image: alpine
      args:
         - sleep
         - 1d