---
apiVersion: v1
kind: Pod
metadata:
  name: trail2
spec:
  containers:
    - name: life1day
      image: alpine
      args:
        - sleep
        - 1d
      resources:
        limits:
          cpu: 500m
          memory: 256Mi