---
apiVersion: v1
kind: Pod
metadata:
  name: trail5
spec:
  restartPolicy: OnFailure
  initContainers:
    - name: init1
      image: alpine
      args:
         - sleep
         - 30s
  containers:
    - name: httpd
      image: httpd:2.4
     