---
apiVersion: v1
kind: Service
metadata:
  name: spc-svc
spec:
  selector:
    app: spc
  type: NodePort
  ports:
    - name: spc
      nodePort: 31000
      port: 8080
      targetPort: 8080
      