---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: spc-rs
spec:
  minReadySeconds: 5
  replicas: 3
  selector:
    matchLabels:
      app: spc
  template:
    metadata:
      labels:
        app: spc
        env: dev
        version: v3.4.0
    spec:
      restartPolicy: Always
      containers:
        - name: spc
          image: shaikkhajaibrahim/spcjan2024:1.0
          ports:
            - containerPort: 8080