---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs
  labels:
    purpose: test
spec:
  minReadySeconds: 5
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        version: v1.0
        env: dev
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80



---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  selector:
    env: dev
  ports:
    - name: nginx-port
      targetPort: 80
      port: 80