---
apiVersion: v1
kind: ReplicationController
metadata:
  name: trail3-rc
  labels:
    app: nginx
spec:
  minReadySeconds: 10
  replicas: 3
  selector:
    app: nginx
  template:
    metadata:
      labels:
        app: nginx
        env: dev
        version: "1.0"
    spec:
        containers:
          - name: nginx
            image: nginx
            resources:
              limits:
                cpu: 500m
                memory: 1Gi
            