 - name: install utilities
   hosts: all
   become: yes
   tasks:
      - name: install git
        ansible.builtin.apt:
          name: git
          update_cache: yes
          state: present
      - name: install tree
        ansible.builtin.apt:
          name: tree
          update_cache: yes
          state: present
      