---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ns-deploy
  namespace: dev
spec:
  minReadySeconds: 30
  progressDeadlineSeconds: 600
  replicas: 2
  selector:
    matchLabels:
      app: httpd
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 40%
      maxUnavailable: 40%
  template:
    metadata:
      labels:
        app: httpd
        ver: "v1.0"
    spec:
      containers:
        - name: apache
          image: httpd:2.4
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
          ports:
            - containerPort: 80