---
apiVersion: v1
kind: Pod
metadata:
  name: a-pod
  labels:
    name: vsh
spec:
  containers:
  - name: a-cntr
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
