---
apiVersion: v1
kind: Pod
metadata:
  name: affinity
  labels:
    name: affinity
spec:
  affinity: 
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              name: vsh
          topologyKey: kubernetes.io/hostname
          
  containers:
    - name: affinity
      image: httpd:2.4
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      
